---
- name: Main playbook
  become: true
  hosts:
    - localhost

  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_port: 8080