---
- name: Main playbook
  become: true
  hosts:
    - localhost

  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx

    - name: Ensure nginx is configured
      ansible.builtin.template:
        src: default.conf.j2
        dest: /etc/nginx/http.d/default.conf
        mode: '640'
      vars:
        nginx_port: 8080
