---
- name: Main playbook
  hosts:
    - localhost
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx

    - name: Configure nginx
      ansible.builtin.template:
        src: default.conf.j2
        dest: /etc/nginx/http.d/default.conf
        mode: '640'
      vars:
        nginx_port: 8080
